Repository JakinChan200/CS180_Roald, pull requests merged in 2022-05, with the labels that each got.

#42 Move Form and Decorate Home Page, Add User Context to Countries and Form
  README.md
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/addvideo.svg
  client/src/assets/chartsvg.svg
  client/src/components/Country/PubForm/PubForm.css
  client/src/components/Country/PubForm/PubForm.tsx
  client/src/components/Country/SearchBar/SearchBar.tsx
  client/src/components/Home/PubForm/PubForm.css
  client/src/components/Home/PubForm/PubForm.tsx
  client/src/components/Hover/Hover.css
  client/src/constants/axiosConfig.ts
  client/src/constants/types/videoTypes.ts
  client/src/contexts/.gitkeep
  client/src/contexts/UserContext.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/Country/Country.tsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.jsx
  client/src/pages/Home/Home.tsx
  server/csv/USERS.csv
  server/database/users.json
  server/index.js
Labels: enhancement

#53 Added average time to trend and graphs of likes vs. trending date
  client/src/pages/Country/Country.tsx
  server/database/database.js
  server/package-lock.json
Labels: enhancement

#54 Added scroll functionality and the other graphs for Query Metrics
  client/src/components/Country/LineGraph/LineGraph.tsx
  client/src/pages/Country/Country.tsx
Labels: enhancement

#56 Jchan419 create pie chart
  client/package-lock.json
  client/package.json
  client/src/components/Home/PubForm/PieChart/PieChart.css
  client/src/components/Home/PubForm/PieChart/PieChart.tsx
  client/src/pages/Country/Country.tsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.tsx
  server/csv/USERS.csv
  server/database/database.js
  server/database/users.json
  server/package-lock.json
Labels: enhancement

#55 Add react-devtools
  client/package-lock.json
  client/package.json
  client/public/index.html
Labels: enhancement

#61 Jchan419 fix pie chart overlap
  client/src/components/Home/PubForm/PieChart/PieChart.tsx
  client/src/pages/Home/Home.css
Labels: bug, enhancement

#62 Removed duplicate X values and averaged their Y values from graphs
  client/src/components/Country/LineGraph/LineGraph.tsx
Labels: bug

#65 Fix Experimental Results
  client/src/components/Country/LineGraph/LineGraph.tsx
  client/src/pages/Country/Country.tsx
Labels: bug

#64 Added scaling to Line Graphs
  client/src/components/Country/LineGraph/LineGraph.tsx
  client/src/pages/Country/Country.tsx
Labels: enhancement

#66 AppleTater-added-and-fixed-time-of-day
  client/src/pages/Country/Country.tsx
  server/database/database.js
Labels: bug, enhancement

#59 Improve Country Performance
  client/src/App.tsx
  client/src/components/Country/LineGraph/LineGraph.tsx
  client/src/constants/averages.ts
  client/src/constants/types/averageTypes.ts
  client/src/contexts/CountryContext.tsx
  client/src/pages/Country/Country.tsx
  client/src/pages/Country/dataHelper/getData.ts
  client/src/pages/Home/Home.tsx
  server/routes/countries.js
Labels: enhancement

#67 Update Docs
  README.md
Labels: documentation
